on: [push]

jobs:
  print-env-data:
    runs-on: ubuntu-latest
    name: Fetch Shipyard Vars
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch Shipyard Environment
        uses: shipyard/github-action/fetch-shipyard-env@1.0.0
        with:
          api-token: ${{ secrets.SHIPYARD_API_TOKEN }}
          timeout-minutes: "10"
      - name: Print Env Data
        run: |
          echo $SHIPYARD_ENVIRONMENT_URL
        shell: bash
