on: [push]

jobs:
  print-env-data:
    runs-on: ubuntu-latest
    name: Fetch Shipyard Vars
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Integrate Shipyard
        uses: shipyard/shipyard-action@1.0.0
        with:
          api-token: ${{ secrets.SHIPYARD_API_TOKEN }}
          timeout-minutes: "10"
      - name: Print Env Data
        run: |
          export CYPRESS_BASE_URL=${SHIPYARD_ENVIRONMENT_URL}
          export CYPRESS_BYPASS_TOKEN=${SHIPYARD_BYPASS_TOKEN}
          env | grep -e SHIPYARD -e CYPRESS
        shell: bash
